# Generated by Django 2.2.12 on 2021-06-09 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='titles',
            old_name='title_name',
            new_name='title',
        ),
    ]
