# Generated by Django 2.2.12 on 2021-06-09 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20210609_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
