# Generated by Django 2.2.12 on 2021-06-14 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_likedpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikedPost',
        ),
    ]
